### ISSUE TITLE
DiyHue and Home-assistant

### ISSUE THREAD

**Issue by NightFalcon650** [diyhue/ReadTheDocs#20]
Hello
i've checked for messages about howto integrate diyhue in Home-assistant, but i can't find a good explanation.
I tried it with the Hue addon in home-assistant but it doesn't discover DiyHue. Even adding it manualy it isn't working and i'm getting a error message in the configuration.yaml

Can somebody help me integrating DiyHue in Home-assistant?

Thanks in advance,

Mark

**Comment by mariusmotea** [comment]
The pair process with home assistant is the same like with any hue application. Did you press the link button in order to allow home assistant to pair and create an user on diuhue?

**Comment by Mevel** [comment]
I have diyhue running with home assistant. Got autodiscoverd without issues.
pressing the link button while adding in home assistant.

Need more Infos and error logs if problem persists

**Comment by NightFalcon650** [comment]
Thanks for the reactions.
First i tried to link it through the webinterface. Also tried it through http://{IP_ADDRESS}/hue/linkbutton but in all cases i can't link it.

Down below the log message in the Home-assistant webpage
![image](https://user-images.githubusercontent.com/7109209/80175476-f4dfa280-85f5-11ea-8309-a0c67622e546.png)

Further the ha core logs
![image](https://user-images.githubusercontent.com/7109209/80176615-784ec300-85f9-11ea-8b7c-5c510de2d883.png)

Ha supervisor logs
![image](https://user-images.githubusercontent.com/7109209/80176685-b1873300-85f9-11ea-9456-3e14d848e01a.png)

**Comment by Mevel** [comment]
Is your bridge autodiscoverd by homeassistant?

The logs don't show much related to diyhue bind process.

**Comment by NightFalcon650** [comment]
nope, it hasn't been autodiscoverd.
When i try to add the diyhue through configuration -> Integrations and then search for philips Hue immediately get the message that it can't find the bridge.

![image](https://user-images.githubusercontent.com/7109209/80184999-e7351780-860b-11ea-8056-8cb1b9dcbca1.png)
