### ISSUE TITLE
Install on Host / Trouble with Port 80 and then 443 ;/

### ISSUE THREAD

**Issue by Br3b** [diyhue/ReadTheDocs#4]
Hey there,
I'm pretty new to Linux so there is still missing some basic knowledge. sorry about that.
I'm already running deConz with the ZigBee module and pihole on my Raspberry Pi 2. 
when I wanted to install diyHue on the host it always said:
"ERROR!! Port 80 already in use. Close the application that use this port and try again."

after figuring out I finally changed successfully the port of both, deconz and pihole, because both of them wanted to use port 80.

Then I run the install again and got another Error...
"ERROR!! Port 443 already in use. Close the application that use this port and try again."

can someone please help me out?
actually, I just want to install diyHue to being able to use the Philips HueSync Software for PC Ambilight.

appreciate any help in advance! :)
Greetings Br3b

**Comment by Mevel** [comment]
https://diyhue.readthedocs.io/en/latest/lights/raspbee.html#deconz-installation

Deconz is using port 80 per default. You need to change it. If deconz is new installed look in `/lib/... ` for deconz config. 

<blockquote><div><strong><a href="https://diyhue.readthedocs.io/en/latest/lights/raspbee.html#deconz-installation">Raspbee — diyHue 1.0 documentation</a></strong></div></blockquote>

**Comment by ghost** [comment]
Run `netstat -a | grep 443`
This should list the service using port 443 so you know which service to edit

**Comment by Br3b** [comment]
Hey there thanks for your fast answers!
@MevelI already changed deconz to use port 8081.
my "/etc/systemd/system/deconz.service" is completely empty.
when I type in sudo systemctl cat deconz it says "--http-port=8081"
so I actually changed the port successfully.

@cheesemarathon i checked out and deconz is also using port 443.

so the question is if diyhue needs to use port 443 as well and if, how to change deconz from using port 443 as well :/

**Comment by ghost** [comment]
You should be able to change the port used by deconz the same way you did for port 80. But I believe that port is for web socket support, so changing it may screw things up. @mariusmotea should probably look at this also, incase it's something he has seen before
We may need to update documentation to deal with this.

**Comment by mariusmotea** [comment]
I update Deconz one month ago and i did not saw Deconz to listen on 443. Maybe you did not specify the websocket port in systemd service file like in the example i provide and Deconz is using that port for websocket now.

**Comment by Br3b** [comment]
to be honest i dont know how and where i changed the port :/ and i cant find anymore.
but yes i did not changed it in deconz.service 
so what @mariusmotea wrote probably will be the reason. 
the question is just why my /etc/systemd/system/deconz.service" is completely empty.
so there is no way to change anything :7

**Comment by mariusmotea** [comment]
here the documentation need to be fixed. is /lib/systemd/system/deconz.service

**Comment by Br3b** [comment]
@mariusmotea ah yeah thanks this is it. I think I used this path to change the port from 80 to 8081. 
and yes it says --http-port=8081
but there is nothing about the websocket port 443 which I'm having trouble with.
Do you know where to change the websocket port from 443 to something else so I finally can install diyhue?
thanks in advance!

**Comment by Mevel** [comment]
i use this and it works

```[Unit]
Description=deCONZ: ZigBee gateway -- REST API
Wants=deconz-init.service deconz-update.service

[Service]
User=1000
ExecStart=/usr/bin/deCONZ -platform minimal --http-port=8080 --upnp=0 --ws-port=8081
Restart=on-failure
StartLimitInterval=60
AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_KILL CAP_SYS_BOOT CAP_SYS_TIME

[Install]
WantedBy=multi-user.target
```


in `/lib/systemd/system/deconz.service`

From Deconz REST API Docs

> The Websocket server is started on an unused proxy friendly port which, depending on the system, is either 443, 8080, 8088, 20877, or any other unused random port.

If you dont specify it, it uses 443.

[Websocket Doumentation Deconz](https://dresden-elektronik.github.io/deconz-rest-doc/websocket/)

**Comment by Br3b** [comment]
oh man, I just replaced --http-port=yxz and not --ws-port=xyz
finally it worked out, thanks a lot!
now I just have to figure out how to implement my Philips light strip plus to the entertainment area to be able to use it in HueSync on my PC.. but seems to don't find a compatible light :/

**Comment by mariusmotea** [comment]
I have some bad news, Deconz don't suport hue entertainment. I implement an emulation using regular hue api protocol that is much slower. But WS2812 strip for real entertainment effect.

**Comment by Br3b** [comment]
okay, but how are you implementing lights with pi and ZigBee module to the emulated hue?
if this is somehow possible I would implement the Philips light strip directly to diyHue.
I'm trying to connect the Philips light strip directly to diyHue described in diyhue.readthedocs but my hue app keeps crashing when navigating to light settings or software update.
reinstalled and restart already tried =/
Greetings

**Comment by Br3b** [comment]
well well. I reinstalled diyhue and reset my phoscon gateway and then I just connected the 1 Philips light stipe and no other Osram smart+.
now the hue app runs stable and is able to choose the strip for the entertainment area. 
BUT it says that the Philips light stripe needs an update and if I do so it says failure.
how can I update the firmware of specific lights?
Greetings

**Comment by ghost** [comment]
@Br3b If its a genuine phillips light, the only way to update it is to pair it to the genuine hue bridge, connect to the genuine hue bridge with the app (you can pair more than one bridge in the app) and install the update through the genuine hue bridge with the app.
